repo:
  file_filters:
    excluded_patterns:
      - "*/.venv/*"
      - "*/env/*"
      - "*/virtualenv/*"
      - "*/node_modules/*"
      - "*/bower_components/*"
      - "*/jspm_packages/*"
      - "*/.git/*"
      - "*/.svn/*"
      - "*/.hg/*"
      - "*/.bzr/*"
      - "*/__pycache__/*"
      - "*/build*/*"
      - "*/dist*/*"
      - "*/bower_components/*"
      - "*/jspm_packages/*"
      - "*/lib-cov/*"
      - "*/htmlcov/*"
      - "*/bin*/*"
      - "*/out*/*"
      - "*yarn.lock"
      - "*pnpm-lock.yaml"
      - "*npm-shrinkwrap.json"
      - "*poetry.lock"
      - "*Pipfile.lock"
      - "*requirements.txt.lock"
      - "*Cargo.lock"
      - "*composer.lock"
      - "*.lock"
      - "*.DS_Store"
      - "*.Thumbs.db"
      - "*desktop.ini"
      - "*.lnk"
      - "*.env.*"
      - "*.env"
      - "*.cfg"
      - "*.ini" 
      - "*.flaskenv"
      - "*.gitignore"
      - "*.gitattributes"
      - "*.gitmodules"
      - "*.github"
      - "*.gitlab-ci.yml"
      - "*.prettierrc"
      - "*.eslintrc"
      - "*.eslintignore"
      - "*.stylelintrc"
      - "*.editorconfig"
      - "*.jshintrc"
      - "*.pylintrc"
      - "*.flake8"
      - "*mypy.ini"
      - "*pyproject.toml"
      - "*tsconfig.json"
      - "*webpack.config.js"
      - "*babel.config.js"
      - "*rollup.config.js"
      - "*jest.config.js"
      - "*karma.conf.js"
      - "*vite.config.js"
      - "*next.config.js"
      - "*.min.js"
      - "*.min.css"
      - "*.bundle.js"
      - "*.bundle.css"
      - "*.map"
      - "*.gz"
      - "*.zip"
      - "*.tar"
      - "*.tgz"
      - "*.rar"
      - "*.7z"
      - "*.iso"
      - "*.dmg"
      - "*.img"
      - "*.msix"
      - "*.appx"
      - "*.appxbundle"
      - "*.xap"
      - "*.ipa"
      - "*.deb"
      - "*.rpm"
      - "*.msi"
      - "*.exe"
      - "*.dll"
      - "*.so"
      - "*.dylib"
      - "*.o"
      - "*.obj"
      - "*.jar"
      - "*.war"
      - "*.ear"
      - "*.jsm"
      - "*.class"
      - "*.pyc"
      - "*.pyd"
      - "*.pyo"
      - "*.a"
      - "*.lib"
      - "*.lo"
      - "*.la"
      - "*.slo"
      - "*.dSYM"
      - "*.egg"
      - "*.egg-info"
      - "*.dist-info"
      - "*.eggs"
      - "*.nyc_output"
      - "*.tox"
      - "*output"
    extra_excluded_patterns: []

  repository:
    max_size_mb: 50000

  file_extensions:
    code_extensions:
      - ".py"
      - ".java"
      - ".cpp"
      - ".cc"
      - ".cxx"
      - ".c"
      - ".h"
      - ".hpp"
      - ".xml"
      - ".java"
    doc_extensions:
      - ".txt"