rag:
  embedder:
    client_class: DashScopeEmbedder
    # client_class: HuggingfaceEmbedder
    model: text-embedding-v4
    # model: intfloat/multilingual-e5-large-instruct
    model_kwargs:
      dimensions: 256
      encoding_format: float
      batch_size: 10

    sketch_filling: true
    force_embedding: false

  retriever:
    top_k: 20

  hybrid:
    enabled: true
    bm25:
      top_k: 100
      k1: 1.2
      b: 0.75
  
  # Dynamic splitter configuration - automatically selects appropriate splitter
  use_dynamic_splitter: true
 
  # Text splitter configuration for natural language documents
  text_splitter:
    split_by: word
    chunk_size: 256
    chunk_overlap: 32
  # Code splitter configuration for source code files
  code_splitter:
    split_by: word
    chunk_size: 256
    chunk_overlap: 32

  code_understanding:
    provider: dashscope
    client_class: DashScopeClient
    model: qwen3-8b
    model_kwargs:
      temperature: 0.7
      top_p: 0.8
      max_tokens: 2048