# @package _global_
# Configuration for text generation
# Controls model parameters like temperature and top_p for text generation

defaults:
  - _self_

provider: dashscope
model: qwen3-coder-plus-2025-07-22
model_kwargs:
  temperature: 0.7
  top_p: 0.8