# @package _global_
# Configuration for RAG system
# Includes hybrid search (BM25 + embeddings), text chunking, and code understanding settings

defaults:
  - _self_

embedder:
  client_class: DashScopeEmbedder
  # client_class: HuggingfaceEmbedder
  model: text-embedding-v4
  # model: intfloat/multilingual-e5-large-instruct
  model_kwargs:
    dimensions: 256
    encoding_format: float
    batch_size: 10

  sketch_filling: true
  force_embedding: false

retriever:
  top_k: 5

hybrid:
  enabled: true
  bm25:
    top_k: 5
    k1: 1.2
    b: 0.75

text_splitter:
  split_by: word
  chunk_size: 512
  chunk_overlap: 32

code_understanding:
  provider: dashscope
  client_class: DashScopeClient
  model: qwen-plus
  model_kwargs:
    temperature: 0.7
    top_p: 0.8
    max_tokens: 2048